import { StyleSheet } from 'react-native';

export const welcomeStyles = StyleSheet.create({
  scrollContent: { flexGrow: 1, justifyContent: 'space-between' },
  topZone: { alignItems: 'center', paddingHorizontal: 24 },
  logo: { fontSize: 26, fontWeight: '800', textAlign: 'center', marginTop: 4 },
  chips: { flexDirection: 'row', gap: 10, marginTop: 14, flexWrap: 'wrap', justifyContent: 'center' },
  chip: { borderRadius: 999, paddingHorizontal: 14, paddingVertical: 8 },
  chipShadow: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
  },
  chipText: { fontSize: 13, fontWeight: '500' },
  sheet: {
    marginTop: 18,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 24,
    paddingTop: 24,
  },
  title: { fontSize: 28, fontWeight: '800', lineHeight: 34 },
  subtitle: { fontSize: 14, lineHeight: 20, marginTop: 8 },
  features: { flexDirection: 'row', gap: 10, marginTop: 18 },
  feature: { flex: 1, borderRadius: 16, paddingVertical: 12, alignItems: 'center', gap: 6 },
  featureIcon: { fontSize: 22 },
  featureLabel: { fontSize: 12, fontWeight: '600', textAlign: 'center' },
  primaryText: { color: '#fff', fontSize: 16, fontWeight: '700' },
  ghost: {
    minHeight: 44,
    borderRadius: 14,
    borderWidth: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    paddingVertical: 14,
  },
  ghostText: { fontSize: 16, fontWeight: '700' },
});
